name: Release

on:
  workflow_dispatch:
    inputs:
      tagVersion:
        type: string
        description: Tag version
        required: true
        pattern: '^v\d+\.\d+\.\d+$'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: GitHub Action to unlock git-crypt secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.1.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Bump version
        uses: DoubleSymmetry/android-version-actions@v1.3
        with:
          gradlePath: app/build.gradle.kts
          versionName: ${{ github.event.inputs.tagVersion }}

      - name: Create Github Release
        run: gh release create ${{ github.event.inputs.tagVersion }} --title "${{ github.event.inputs.tagVersion }}" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
