name: Release

on:
  workflow_dispatch:
    inputs:
      tagVersion:
        type: string
        description: Tag version
        required: true
        pattern: '^v\d+\.\d+\.\d+$'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Tag current version
        run: |
          git tag ${{ github.event.inputs.tagVersion }}
          git push origin ${{ github.event.inputs.tagVersion }}

      - name: Create Github Release
        run: gh release create ${{ github.event.inputs.tagVersion }} --title "${{ github.event.inputs.tagVersion }}" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
